//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStock.ServiceWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsUtilisateur", Namespace="http://schemas.datacontract.org/2004/07/WcfGestionStock.ClassGestionStock")]
    [System.SerializableAttribute()]
    public partial class ClsUtilisateur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotDePasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocieteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Statut {
            get {
                return this.Id_StatutField;
            }
            set {
                if ((this.Id_StatutField.Equals(value) != true)) {
                    this.Id_StatutField = value;
                    this.RaisePropertyChanged("Id_Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotDePasse {
            get {
                return this.MotDePasseField;
            }
            set {
                if ((object.ReferenceEquals(this.MotDePasseField, value) != true)) {
                    this.MotDePasseField = value;
                    this.RaisePropertyChanged("MotDePasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Societe {
            get {
                return this.SocieteField;
            }
            set {
                if ((object.ReferenceEquals(this.SocieteField, value) != true)) {
                    this.SocieteField = value;
                    this.RaisePropertyChanged("Societe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsStockProduit", Namespace="http://schemas.datacontract.org/2004/07/WcfGestionStock.ClassGestionStock")]
    [System.SerializableAttribute()]
    public partial class ClsStockProduit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CategorieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_FournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_CategorieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Prix_VenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Quantite_StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SommeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Categorie {
            get {
                return this.Id_CategorieField;
            }
            set {
                if ((this.Id_CategorieField.Equals(value) != true)) {
                    this.Id_CategorieField = value;
                    this.RaisePropertyChanged("Id_Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Fournisseur {
            get {
                return this.Id_FournisseurField;
            }
            set {
                if ((this.Id_FournisseurField.Equals(value) != true)) {
                    this.Id_FournisseurField = value;
                    this.RaisePropertyChanged("Id_Fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Categorie {
            get {
                return this.Nom_CategorieField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_CategorieField, value) != true)) {
                    this.Nom_CategorieField = value;
                    this.RaisePropertyChanged("Nom_Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Produit {
            get {
                return this.Nom_ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_ProduitField, value) != true)) {
                    this.Nom_ProduitField = value;
                    this.RaisePropertyChanged("Nom_Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prix_Vente {
            get {
                return this.Prix_VenteField;
            }
            set {
                if ((this.Prix_VenteField.Equals(value) != true)) {
                    this.Prix_VenteField = value;
                    this.RaisePropertyChanged("Prix_Vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantite_Stock {
            get {
                return this.Quantite_StockField;
            }
            set {
                if ((this.Quantite_StockField.Equals(value) != true)) {
                    this.Quantite_StockField = value;
                    this.RaisePropertyChanged("Quantite_Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Somme {
            get {
                return this.SommeField;
            }
            set {
                if ((this.SommeField.Equals(value) != true)) {
                    this.SommeField = value;
                    this.RaisePropertyChanged("Somme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsPanier", Namespace="http://schemas.datacontract.org/2004/07/WcfGestionStock.ClassGestionStock")]
    [System.SerializableAttribute()]
    public partial class ClsPanier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Prix_VenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SommeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Client {
            get {
                return this.Id_ClientField;
            }
            set {
                if ((this.Id_ClientField.Equals(value) != true)) {
                    this.Id_ClientField = value;
                    this.RaisePropertyChanged("Id_Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_produit {
            get {
                return this.Id_produitField;
            }
            set {
                if ((this.Id_produitField.Equals(value) != true)) {
                    this.Id_produitField = value;
                    this.RaisePropertyChanged("Id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_produit {
            get {
                return this.Nom_produitField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_produitField, value) != true)) {
                    this.Nom_produitField = value;
                    this.RaisePropertyChanged("Nom_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prix_Vente {
            get {
                return this.Prix_VenteField;
            }
            set {
                if ((this.Prix_VenteField.Equals(value) != true)) {
                    this.Prix_VenteField = value;
                    this.RaisePropertyChanged("Prix_Vente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Somme {
            get {
                return this.SommeField;
            }
            set {
                if ((this.SommeField.Equals(value) != true)) {
                    this.SommeField = value;
                    this.RaisePropertyChanged("Somme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsCmdClient", Namespace="http://schemas.datacontract.org/2004/07/WcfGestionStock.ClassGestionStock")]
    [System.SerializableAttribute()]
    public partial class ClsCmdClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_cmdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_livraisonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_utilisateurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Prix_quantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Prix_unitaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SommeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_cmd {
            get {
                return this.Date_cmdField;
            }
            set {
                if ((this.Date_cmdField.Equals(value) != true)) {
                    this.Date_cmdField = value;
                    this.RaisePropertyChanged("Date_cmd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_livraison {
            get {
                return this.Date_livraisonField;
            }
            set {
                if ((this.Date_livraisonField.Equals(value) != true)) {
                    this.Date_livraisonField = value;
                    this.RaisePropertyChanged("Date_livraison");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_produit {
            get {
                return this.Id_produitField;
            }
            set {
                if ((this.Id_produitField.Equals(value) != true)) {
                    this.Id_produitField = value;
                    this.RaisePropertyChanged("Id_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_utilisateur {
            get {
                return this.Id_utilisateurField;
            }
            set {
                if ((this.Id_utilisateurField.Equals(value) != true)) {
                    this.Id_utilisateurField = value;
                    this.RaisePropertyChanged("Id_utilisateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_produit {
            get {
                return this.Nom_produitField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_produitField, value) != true)) {
                    this.Nom_produitField = value;
                    this.RaisePropertyChanged("Nom_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prix_quantite {
            get {
                return this.Prix_quantiteField;
            }
            set {
                if ((this.Prix_quantiteField.Equals(value) != true)) {
                    this.Prix_quantiteField = value;
                    this.RaisePropertyChanged("Prix_quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prix_unitaire {
            get {
                return this.Prix_unitaireField;
            }
            set {
                if ((this.Prix_unitaireField.Equals(value) != true)) {
                    this.Prix_unitaireField = value;
                    this.RaisePropertyChanged("Prix_unitaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Somme {
            get {
                return this.SommeField;
            }
            set {
                if ((this.SommeField.Equals(value) != true)) {
                    this.SommeField = value;
                    this.RaisePropertyChanged("Somme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsFournisseur", Namespace="http://schemas.datacontract.org/2004/07/WcfGestionStock.ClassGestionStock")]
    [System.SerializableAttribute()]
    public partial class ClsFournisseur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocieteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Societe {
            get {
                return this.SocieteField;
            }
            set {
                if ((object.ReferenceEquals(this.SocieteField, value) != true)) {
                    this.SocieteField = value;
                    this.RaisePropertyChanged("Societe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsCmdFournisseur", Namespace="http://schemas.datacontract.org/2004/07/WcfGestionStock.ClassGestionStock")]
    [System.SerializableAttribute()]
    public partial class ClsCmdFournisseur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_cmdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_receptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_fournisseurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_produitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Prix_unitaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocieteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SommeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_cmd {
            get {
                return this.Date_cmdField;
            }
            set {
                if ((this.Date_cmdField.Equals(value) != true)) {
                    this.Date_cmdField = value;
                    this.RaisePropertyChanged("Date_cmd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_reception {
            get {
                return this.Date_receptionField;
            }
            set {
                if ((this.Date_receptionField.Equals(value) != true)) {
                    this.Date_receptionField = value;
                    this.RaisePropertyChanged("Date_reception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_fournisseur {
            get {
                return this.Id_fournisseurField;
            }
            set {
                if ((this.Id_fournisseurField.Equals(value) != true)) {
                    this.Id_fournisseurField = value;
                    this.RaisePropertyChanged("Id_fournisseur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_produit {
            get {
                return this.Nom_produitField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_produitField, value) != true)) {
                    this.Nom_produitField = value;
                    this.RaisePropertyChanged("Nom_produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Prix_unitaire {
            get {
                return this.Prix_unitaireField;
            }
            set {
                if ((this.Prix_unitaireField.Equals(value) != true)) {
                    this.Prix_unitaireField = value;
                    this.RaisePropertyChanged("Prix_unitaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Societe {
            get {
                return this.SocieteField;
            }
            set {
                if ((object.ReferenceEquals(this.SocieteField, value) != true)) {
                    this.SocieteField = value;
                    this.RaisePropertyChanged("Societe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Somme {
            get {
                return this.SommeField;
            }
            set {
                if ((this.SommeField.Equals(value) != true)) {
                    this.SommeField = value;
                    this.RaisePropertyChanged("Somme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loguer", ReplyAction="http://tempuri.org/IService1/LoguerResponse")]
        bool Loguer(string LoginUtilisateur, string MotDePasse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loguer", ReplyAction="http://tempuri.org/IService1/LoguerResponse")]
        System.Threading.Tasks.Task<bool> LoguerAsync(string LoginUtilisateur, string MotDePasse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireTableUtilisateurSql", ReplyAction="http://tempuri.org/IService1/LireTableUtilisateurSqlResponse")]
        GestionDeStock.ServiceWCF.ClsUtilisateur[] LireTableUtilisateurSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireTableUtilisateurSql", ReplyAction="http://tempuri.org/IService1/LireTableUtilisateurSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsUtilisateur[]> LireTableUtilisateurSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifUtilisateurSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifUtilisateurSqlResponse")]
        void AjoutSupModifUtilisateurSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifUtilisateurSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifUtilisateurSqlResponse")]
        System.Threading.Tasks.Task AjoutSupModifUtilisateurSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireStockProduitSql", ReplyAction="http://tempuri.org/IService1/LireStockProduitSqlResponse")]
        GestionDeStock.ServiceWCF.ClsStockProduit[] LireStockProduitSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireStockProduitSql", ReplyAction="http://tempuri.org/IService1/LireStockProduitSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsStockProduit[]> LireStockProduitSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SommeProduitSql", ReplyAction="http://tempuri.org/IService1/SommeProduitSqlResponse")]
        GestionDeStock.ServiceWCF.ClsStockProduit[] SommeProduitSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SommeProduitSql", ReplyAction="http://tempuri.org/IService1/SommeProduitSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsStockProduit[]> SommeProduitSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireCategorieSql", ReplyAction="http://tempuri.org/IService1/LireCategorieSqlResponse")]
        GestionDeStock.ServiceWCF.ClsStockProduit[] LireCategorieSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireCategorieSql", ReplyAction="http://tempuri.org/IService1/LireCategorieSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsStockProduit[]> LireCategorieSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifProduitSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifProduitSqlResponse")]
        void AjoutSupModifProduitSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifProduitSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifProduitSqlResponse")]
        System.Threading.Tasks.Task AjoutSupModifProduitSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireTablePanierSql", ReplyAction="http://tempuri.org/IService1/LireTablePanierSqlResponse")]
        GestionDeStock.ServiceWCF.ClsPanier[] LireTablePanierSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireTablePanierSql", ReplyAction="http://tempuri.org/IService1/LireTablePanierSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsPanier[]> LireTablePanierSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SommePanierSql", ReplyAction="http://tempuri.org/IService1/SommePanierSqlResponse")]
        GestionDeStock.ServiceWCF.ClsPanier[] SommePanierSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SommePanierSql", ReplyAction="http://tempuri.org/IService1/SommePanierSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsPanier[]> SommePanierSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifPanierSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifPanierSqlResponse")]
        void AjoutSupModifPanierSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifPanierSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifPanierSqlResponse")]
        System.Threading.Tasks.Task AjoutSupModifPanierSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireCmdClientSql", ReplyAction="http://tempuri.org/IService1/LireCmdClientSqlResponse")]
        GestionDeStock.ServiceWCF.ClsCmdClient[] LireCmdClientSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireCmdClientSql", ReplyAction="http://tempuri.org/IService1/LireCmdClientSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsCmdClient[]> LireCmdClientSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SommeCmdClientSql", ReplyAction="http://tempuri.org/IService1/SommeCmdClientSqlResponse")]
        GestionDeStock.ServiceWCF.ClsCmdClient[] SommeCmdClientSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SommeCmdClientSql", ReplyAction="http://tempuri.org/IService1/SommeCmdClientSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsCmdClient[]> SommeCmdClientSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifCmdClientSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifCmdClientSqlResponse")]
        void AjoutSupModifCmdClientSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifCmdClientSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifCmdClientSqlResponse")]
        System.Threading.Tasks.Task AjoutSupModifCmdClientSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireFournisseurSql", ReplyAction="http://tempuri.org/IService1/LireFournisseurSqlResponse")]
        GestionDeStock.ServiceWCF.ClsFournisseur[] LireFournisseurSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireFournisseurSql", ReplyAction="http://tempuri.org/IService1/LireFournisseurSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsFournisseur[]> LireFournisseurSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifFournisseurSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifFournisseurSqlResponse")]
        void AjoutSupModifFournisseurSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifFournisseurSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifFournisseurSqlResponse")]
        System.Threading.Tasks.Task AjoutSupModifFournisseurSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireCmdFournisseurSql", ReplyAction="http://tempuri.org/IService1/LireCmdFournisseurSqlResponse")]
        GestionDeStock.ServiceWCF.ClsCmdFournisseur[] LireCmdFournisseurSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LireCmdFournisseurSql", ReplyAction="http://tempuri.org/IService1/LireCmdFournisseurSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsCmdFournisseur[]> LireCmdFournisseurSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifCmdFournisseurSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifCmdFournisseurSqlResponse")]
        void AjoutSupModifCmdFournisseurSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutSupModifCmdFournisseurSql", ReplyAction="http://tempuri.org/IService1/AjoutSupModifCmdFournisseurSqlResponse")]
        System.Threading.Tasks.Task AjoutSupModifCmdFournisseurSqlAsync(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SommeCmdFournisseurSql", ReplyAction="http://tempuri.org/IService1/SommeCmdFournisseurSqlResponse")]
        GestionDeStock.ServiceWCF.ClsCmdFournisseur[] SommeCmdFournisseurSql(string _RequeteSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SommeCmdFournisseurSql", ReplyAction="http://tempuri.org/IService1/SommeCmdFournisseurSqlResponse")]
        System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsCmdFournisseur[]> SommeCmdFournisseurSqlAsync(string _RequeteSql);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GestionDeStock.ServiceWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GestionDeStock.ServiceWCF.IService1>, GestionDeStock.ServiceWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Loguer(string LoginUtilisateur, string MotDePasse) {
            return base.Channel.Loguer(LoginUtilisateur, MotDePasse);
        }
        
        public System.Threading.Tasks.Task<bool> LoguerAsync(string LoginUtilisateur, string MotDePasse) {
            return base.Channel.LoguerAsync(LoginUtilisateur, MotDePasse);
        }
        
        public GestionDeStock.ServiceWCF.ClsUtilisateur[] LireTableUtilisateurSql(string _RequeteSql) {
            return base.Channel.LireTableUtilisateurSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsUtilisateur[]> LireTableUtilisateurSqlAsync(string _RequeteSql) {
            return base.Channel.LireTableUtilisateurSqlAsync(_RequeteSql);
        }
        
        public void AjoutSupModifUtilisateurSql(string _RequeteSql) {
            base.Channel.AjoutSupModifUtilisateurSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task AjoutSupModifUtilisateurSqlAsync(string _RequeteSql) {
            return base.Channel.AjoutSupModifUtilisateurSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsStockProduit[] LireStockProduitSql(string _RequeteSql) {
            return base.Channel.LireStockProduitSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsStockProduit[]> LireStockProduitSqlAsync(string _RequeteSql) {
            return base.Channel.LireStockProduitSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsStockProduit[] SommeProduitSql(string _RequeteSql) {
            return base.Channel.SommeProduitSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsStockProduit[]> SommeProduitSqlAsync(string _RequeteSql) {
            return base.Channel.SommeProduitSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsStockProduit[] LireCategorieSql(string _RequeteSql) {
            return base.Channel.LireCategorieSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsStockProduit[]> LireCategorieSqlAsync(string _RequeteSql) {
            return base.Channel.LireCategorieSqlAsync(_RequeteSql);
        }
        
        public void AjoutSupModifProduitSql(string _RequeteSql) {
            base.Channel.AjoutSupModifProduitSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task AjoutSupModifProduitSqlAsync(string _RequeteSql) {
            return base.Channel.AjoutSupModifProduitSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsPanier[] LireTablePanierSql(string _RequeteSql) {
            return base.Channel.LireTablePanierSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsPanier[]> LireTablePanierSqlAsync(string _RequeteSql) {
            return base.Channel.LireTablePanierSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsPanier[] SommePanierSql(string _RequeteSql) {
            return base.Channel.SommePanierSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsPanier[]> SommePanierSqlAsync(string _RequeteSql) {
            return base.Channel.SommePanierSqlAsync(_RequeteSql);
        }
        
        public void AjoutSupModifPanierSql(string _RequeteSql) {
            base.Channel.AjoutSupModifPanierSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task AjoutSupModifPanierSqlAsync(string _RequeteSql) {
            return base.Channel.AjoutSupModifPanierSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsCmdClient[] LireCmdClientSql(string _RequeteSql) {
            return base.Channel.LireCmdClientSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsCmdClient[]> LireCmdClientSqlAsync(string _RequeteSql) {
            return base.Channel.LireCmdClientSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsCmdClient[] SommeCmdClientSql(string _RequeteSql) {
            return base.Channel.SommeCmdClientSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsCmdClient[]> SommeCmdClientSqlAsync(string _RequeteSql) {
            return base.Channel.SommeCmdClientSqlAsync(_RequeteSql);
        }
        
        public void AjoutSupModifCmdClientSql(string _RequeteSql) {
            base.Channel.AjoutSupModifCmdClientSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task AjoutSupModifCmdClientSqlAsync(string _RequeteSql) {
            return base.Channel.AjoutSupModifCmdClientSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsFournisseur[] LireFournisseurSql(string _RequeteSql) {
            return base.Channel.LireFournisseurSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsFournisseur[]> LireFournisseurSqlAsync(string _RequeteSql) {
            return base.Channel.LireFournisseurSqlAsync(_RequeteSql);
        }
        
        public void AjoutSupModifFournisseurSql(string _RequeteSql) {
            base.Channel.AjoutSupModifFournisseurSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task AjoutSupModifFournisseurSqlAsync(string _RequeteSql) {
            return base.Channel.AjoutSupModifFournisseurSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsCmdFournisseur[] LireCmdFournisseurSql(string _RequeteSql) {
            return base.Channel.LireCmdFournisseurSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsCmdFournisseur[]> LireCmdFournisseurSqlAsync(string _RequeteSql) {
            return base.Channel.LireCmdFournisseurSqlAsync(_RequeteSql);
        }
        
        public void AjoutSupModifCmdFournisseurSql(string _RequeteSql) {
            base.Channel.AjoutSupModifCmdFournisseurSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task AjoutSupModifCmdFournisseurSqlAsync(string _RequeteSql) {
            return base.Channel.AjoutSupModifCmdFournisseurSqlAsync(_RequeteSql);
        }
        
        public GestionDeStock.ServiceWCF.ClsCmdFournisseur[] SommeCmdFournisseurSql(string _RequeteSql) {
            return base.Channel.SommeCmdFournisseurSql(_RequeteSql);
        }
        
        public System.Threading.Tasks.Task<GestionDeStock.ServiceWCF.ClsCmdFournisseur[]> SommeCmdFournisseurSqlAsync(string _RequeteSql) {
            return base.Channel.SommeCmdFournisseurSqlAsync(_RequeteSql);
        }
    }
}
